### ISSUE TITLE
Sort of "y_term_int" in Strings reference grammar.

### ISSUE THREAD

**Issue by cushionbadak** [SyGuS-Org/docs#1]
https://github.com/SyGuS-Org/docs/blob/41e9f0bf3931d6ace8bc06f72dc601ebe3902bef/language/sygus.tex#L2193

I found this weird declaration at Strings reference grammar. Isn't `y_term_int` an `Int` ?

**Comment by SaswatPadhi** [comment]
Thanks for pointing it out, Jisuk!

You are correct -- it should be an `Int` nonterminal. I will push a fix for this in a moment.

**Comment by cushionbadak** [comment]
https://github.com/SyGuS-Org/docs/blob/7abb35dbf408e2df69d4e47daa7a04acbf0bb7c9/language/sygus.tex#L2183

I forgot to mention this line. For consistency, this line should also be changed.
