### ISSUE TITLE
No rule created for "y_cons" in NRA reference grammar.

### ISSUE THREAD

**Issue by cushionbadak** [SyGuS-Org/docs#2]
https://github.com/SyGuS-Org/docs/blob/e2087076c29746f28c2599afa19ad9cc1cda8c09/language/sygus.tex#L2066-L2081

The NRA reference grammar declares `y_cons` but there are no rules for it.
Considering the relationship between LIA and NIA, `y_cons` will likely have to be taken out of the NRA.

**Comment by SaswatPadhi** [comment]
Thanks, yes you're correct -- The `y_cons` nonterminal is not required in NRA. In LRA (and similarly LIA) it is necessary for the multiplication operators.
